name: PyPI publish release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  metadata:
    runs-on: ubuntu-20.04
    steps:
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Build release
        env:
            TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
            VERSION: $RELEASE_VERSION
        run: |
          pip install twine
          python setup.py sdist
          twine upload --non-interactive dist/*