name: Tests
on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Generate report
        run: |
          pip install -r wallaby_data_access/requirements.txt
          pip install -r tests/requirements.txt
          pytest --cov-report xml --cov
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml,
          verbose: true

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install flake8
          flake8 .