name: Tests
on: [push, pull_request]

jobs:
  codecov:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Clone WALLABY_database
        run: |
          apt-get update && apt-get install -y git lsb-release
          [[ -d WALLABY_database ]] || git clone https://github.com/AusSRC/WALLABY_database.git
      - name: Generate report
        env:
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          WALLABY_DATABASE_PATH: ./WALLABY_database
        run: |
          export PYTHONPATH=$PYTHONPATH:$WALLABY_DATABASE_PATH:.
          pip install -r wallaby_data_access/requirements.txt
          pip install -r tests/requirements.txt
          pytest -v --cov-report xml --cov=./tests
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml,
          verbose: true

  linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: |
          pip install flake8
          flake8 .